---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: repo

outputs:
  - name: artifacts

run:
  path: repo/ci/task/build.sh

caches:
  - path: .m2/repository