resources:
  - name: repo
    type: git
    source:
      branch: master
      uri: https://github.com/promal2006/((repo_name)).git

jobs:
  - name: test
    plan:
      - get: repo
        trigger: true
      - aggregate:
          - task: java-test
            file: repo/ci/task/java_test.yml
